//
//  HKWorkoutActivityType+Extensions.swift
//  Ringfit
//
//  Created by Chloe Chung on 4/21/24.
//

import SwiftUI
import HealthKit

extension HKWorkoutActivityType {
    var workoutName: String {
        switch self {
        case .americanFootball: return "미식 축구"
        case .archery: return "양궁"
        case .australianFootball: return "호주식 축구"
        case .badminton: return "배드민턴"
        case .barre: return "바레"
        case .baseball: return "야구"
        case .basketball: return "농구"
        case .bowling: return "볼링"
        case .boxing: return "복싱"
        case .cardioDance: return "유산소 댄스"
        case .climbing: return "등반"
        case .cooldown: return "쿨다운"
        case .coreTraining: return "코어 트레이닝"
        case .cricket: return "크리켓"
        case .crossCountrySkiing: return "크로스컨트리 스키"
        case .crossTraining: return "크로스 트레이닝"
        case .curling: return "컬링"
        case .cycling: return "사이클링"
        case .discSports: return "디스크 스포츠"
        case .downhillSkiing: return "다운힐 스키"
        case .elliptical: return "일립티컬"
        case .equestrianSports: return "승마"
        case .fencing: return "펜싱"
        case .fitnessGaming: return "피트니스 게임"
        case .fishing: return "낚시"
        case .flexibility: return "유연성"
        case .functionalStrengthTraining: return "기능성 근력 트레이닝"
        case .golf: return "골프"
        case .gymnastics: return "체조"
        case .handball: return "핸드볼"
        case .handCycling: return "핸드 사이클링"
        case .highIntensityIntervalTraining: return "고강도 인터벌 트레이닝"
        case .hiking: return "등산"
        case .hockey: return "하키"
        case .hunting: return "사냥"
        case .jumpRope: return "줄넘기"
        case .kickboxing: return "킥복싱"
        case .lacrosse: return "라크로스"
        case .martialArts: return "무술"
        case .mindAndBody: return "마음과 몸"
        case .mixedCardio: return "혼합 유산소"
        case .mixedMetabolicCardioTraining: return "혼합 대사 유산소 트레이닝"
        case .other: return "기타"
        case .paddleSports: return "패들 스포츠"
        case .pickleball: return "피클볼"
        case .pilates: return "필라테스"
        case .play: return "놀이"
        case .preparationAndRecovery: return "준비 및 회복"
        case .racquetball: return "라켓볼"
        case .rowing: return "조정"
        case .rugby: return "럭비"
        case .running: return "러닝"
        case .sailing: return "세일링"
        case .skatingSports: return "스케이팅 스포츠"
        case .snowSports: return "눈 스포츠"
        case .snowboarding: return "스노우보드"
        case .soccer: return "축구"
        case .socialDance: return "사교 댄스"
        case .softball: return "소프트볼"
        case .squash: return "스쿼시"
        case .stairClimbing: return "계단 오르기"
        case .stairs: return "계단"
        case .stepTraining: return "스텝 트레이닝"
        case .surfingSports: return "서핑 스포츠"
        case .swimBikeRun: return "수영-자전거-런닝"
        case .swimming: return "수영"
        case .tableTennis: return "탁구"
        case .taiChi: return "타이치"
        case .tennis: return "테니스"
        case .trackAndField: return "트랙 앤 필드"
        case .traditionalStrengthTraining: return "전통 근력 트레이닝"
        case .transition: return "전환"
        case .underwaterDiving: return "수중 다이빙"
        case .volleyball: return "배구"
        case .walking: return "걷기"
        case .waterFitness: return "수중 피트니스"
        case .waterPolo: return "수구"
        case .waterSports: return "수상 스포츠"
        case .wrestling: return "레슬링"
        case .yoga: return "요가"
        case .dance: return "댄스"
        case .danceInspiredTraining: return "댄스 인스파이어드 트레이닝"
        case .wheelchairWalkPace: return "휠체어 걷기 속도"
        case .wheelchairRunPace: return "휠체어 달리기 속도"
        @unknown default: return ""
        }
    }
}
